language: python
matrix:
  include:
    - name: "Python 3.4 on Xenial Linux"
      python: 3.4
    - name: "Python 3.5 on Xenial Linux"
      python: 3.5
    - name: "Python 3.6 on Xenial Linux"
      python: 3.6
    - name: "Python 3.7 on Xenial Linux"
      python: 3.7      
    - name: "Python 3.7.4 on macOS"
      os: osx
      osx_image: xcode11
      language: shell
    - name: "Python 3.7.4 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
      install:
        - pip install selenium wget requests certifi
      script:
        - python -V
        - python -m py_compile ci_tests.py configs.py slides.py telescreen.py wikipedia_source.py
        - python telescreen.py -dir ./test/ --headless_test

install:
  - pip3 install selenium wget requests
script:
  - python3 -V
  - python3 -m py_compile ci_tests.py configs.py slides.py telescreen.py wikipedia_source.py
  - python3 telescreen.py -dir ./test/ --headless_test
